### ISSUE TITLE
Implement imgix HTTP GET API frontend

### ISSUE THREAD

**Issue by bradgessler** [h2non/imaginary#131]
Implement a subset of the [imgix API](https://docs.imgix.com/apis/url) so that projects already using imgix can switch over to imaginary without swapping out the imgix client library.

This would also be useful for running imaginary in local and test environments while running production workloads on imgix.

**Comment by bradgessler** [comment]
@davidbirdsong I'm requesting this specifically to run at least a subset of imgix in a docker container for a local development environment that needs to be isolated from the interwebs. Being cognizant of https://github.com/h2non/imaginary#seeking-for-maintainers I'd like to hear your input if imgix would consider going down this path.

**Comment by h2non** [comment]
I have serious doubts about the practical viability of this. imgix API is far more versatile and complex than imaginary one. I don't think this is going to help, even for a reduced API subset the behavior is not the same. If you really need that I would suggest forking the project.

**Comment by h2non** [comment]
Also, the only API redesing I would consider for future versions would be IIIF standard friendly: http://iiif.io/

**Comment by davidbirdsong** [comment]
@bradgessler if you're satisfied w/ a subset of the imgix api that imaginary can support, I'd recommend putting a drop-dead simple http proxy in front of imaginary that simply does url rewrites from imgix api query params to imaginary's api.

since imgix is built around fetching origin content and doesn't use a CMS, you'll have to also figure out how to support exposing origin content to imaginary in a way that is compatible with imgix's configuration. doable, but not trivial either.

**Comment by h2non** [comment]
Yeah, if your are familiar with node.js, you could use rocky for building a simple rewrite http proxy:
https://github.com/h2non/rocky

Or vinxi if you prefer Go: https://github.com/vinxi/vinxi

**Comment by bradgessler** [comment]
Thanks for all the input. I think I'll implement a rubygem that sits a layer above imgix and imaginary. Depending on its configuration it will genereate different URLs to perform image operations.

For now I'll close those ticket to keep the issues clean on the project. I'll update this ticket in the future with a link to the gem for others who run into this same problem.
