### ISSUE TITLE
url param is not encoding colons when fetching from remote source

### ISSUE THREAD

**Issue by saintberry** [h2non/imaginary#176]
I have some horrible remote image sources that have a path like `http://domain.com/img.2017-11-17T16:25:24+13:00.jpg`

If I pass this in as `?url=http://domain.com/img.2017-11-17T16%3A25%3A24%2B13%3A00.jpg` imaginary will send a request for `http://domain.com/img.2017-11-17T16:25:24+13:00.jpg`

If I pass in `?url=http://domain.com/img.2017-11-17T16:25:24+13:00.jpg` imaginary will send a request for `http://domain.com/img.2017-11-17T16:25:24%2013:00.jpg`

I would expect it to correctly encode / decode the url param(?)

**Comment by Dynom** [comment]
The problem is the `+` sign, which is an _unsafe_ character (as denoted in RFC 3986 as the [pchar](https://tools.ietf.org/html/rfc3986#appendix-A)).

Go's [url.Parse()](https://golang.org/src/net/url/url.go#L464) performs an [unescape()](https://golang.org/src/net/url/url.go#L184) on the [path](https://golang.org/src/net/url/url.go#L621) section. Thanks to our HTML spec overlords we've never really gotten around to fix the awkward situation with the `+` representing a whitespace character and is treated differently depending on where it's located in the URL.

After parsing Imaginary uses url.String() in [main.newHTTPRequest()](https://github.com/h2non/imaginary/blob/master/source_http.go#L93), which encodes part of the path. Since `+` wasn't encoded during parsing we now lost the intent of this evil weed, it became ambiguous. Is it intended as a literal `+` or is it intended as an encoded space character. The encoding algorithm now (somewhat correctly) assumes it's an intended literal `+` and encodes the `+` sign, into %20.

The `+` sign is an evil legacy of two conflicting encoding specifications. One around form post data encoding and around URL encoding. If my memory serves me right.

Escaping (URL encoding) the input (the argument to the `url` query parameter) is the proper way of dealing with this situation.

**Comment by saintberry** [comment]
Thanks for the detailed explanation @Dynom. In my case if I encode the full url (double encoding some parts) imaginary can find the source. Thanks!

**Comment by Dynom** [comment]
You're welcome!

For the reference, it's not double encoding what you do in your example.
`img.2017-11-17T16%3A25%3A24%2B13%3A00.jpg` is the correctly encoded form of `img.2017-11-17T16:25:24+13:00.jpg` to pass in the _query string_.
