### ISSUE TITLE
Feature: HMAC URL signature verification

### ISSUE THREAD

**Issue by h2non** [h2non/imaginary#183]
Useful for avoiding service usage from non-trusted remote sources.

The private key for signature verification should be provided at boot time as CLI flag, which would determine the server behavior.

PRs to support this feature is very welcome.

**Comment by Dynom** [comment]
How do you like to see this implemented? I'm assuming that the component that contains the private key isn't a [S.P.A](https://nl.wikipedia.org/wiki/Single_Page_Application), as that would defeat the purpose. So that opens the possibility to go for [JWT](https://jwt.io/).

## JWT
### Pros
- widely used for this particular task
- easy to implement when using the readily available libraries

### Cons
- Quite a different API

## Go vanilla
### Pros
- No need to change the current Imaginary API
### Cons
- A bit harder to implement (we need to document how to sort parameter to produce a reliable checksum, for example)

**Comment by bleleve** [comment]
Hi @h2non ,

Here is my pull request #194 ? Can you review it ?

Best regards,
Benoît.

**Comment by Dynom** [comment]
Part of this have been implemented and are available since version [1.0.15](https://github.com/h2non/imaginary/releases/tag/v1.0.15). Closing the issue!
