### ISSUE TITLE
Change file extension after convert

### ISSUE THREAD

**Issue by mrkwtz** [h2non/imaginary#211]
I wonder why no one brought this up (maybe i'm blind and its in the docs?) but it would be nice if the convert operation would change the file extension (if given) accordingly. Like when i send or specify a local PDF file and convert it to PNG, it should change the extension to .png

**Comment by Dynom** [comment]
If I'm not mistaken, conversion happens because you specify a type. If you specify the type, you know the extension and you could change it yourself quite easily.

Imaginary [doesn't know anything about the filename](https://github.com/h2non/imaginary/blob/master/source_http.go#L71) and therefore cannot change it to anything else. I think the browser you're using tries it's best to produce one for you.
