### ISSUE TITLE
-enable-url-source with builtin cache

### ISSUE THREAD

**Issue by amarCosmospace** [h2non/imaginary#263]
hello,
is there any way to use -enable-url-source and have a built in cache to optimize requests ? Cause i'm having issues with traffic spikes. It loads my server to 60. I'm using it with docker and 25 containers load balanced with traefik.

**Comment by Dynom** [comment]
I think it would be quite complicated to add a cache feature in Imaginary that handels all use-cases and it's therefore not on the list of things we'd like to add to Imaginary.

To solve this item you could:
* Change your Imaginary consumers so that it caches the results instead (e.g. add a CDN in front of Imaginary, CloudFront works quite well, just to give an example)
* Add a reverse-proxy in front of your sources and have that cache the assets for you
* Fork Imaginary and add the right cache strategy for your use-case

**Comment by h2non** [comment]
Not within the scope of the project. Closing.
