### ISSUE TITLE
Fractions result in odd sizes

### ISSUE THREAD

**Issue by Dynom** [h2non/imaginary#30]
Supplying a width with a fraction (e.g. `290.1`) results in awkward behaviour. Specifying `290` results in the correct 290px width. Specifying `290.1` results in 327px width. Similar behaviour is found with the height parameter. specifying a height of (e.g.: 217.1) results in a real hight of 192px.

width | real size
---|---
290 | 290
290.1 | 327

height | real size
---|---
217 | 217
217.1 | 192

We're solving this for now by rounding the input.

Perhaps Imaginary can do any or all of the following:
* "Correctly" handle fractions, but it doesn't seem that libvips supports this.
* Round the input's to circumvent the odd behaviour
* Document it's behaviour

**Comment by h2non** [comment]
Sorry for the delay.
You're right, `libvips` only support integer numbers, and therefore `imaginary` too.

The issue is a bit silly. It's originated in the params parsing process when calling the Go native function `strconv.Atoi()` (which is an alias of `strcon.ParseInt()`), which essentially parses and performs a type cast from a `string` input into an `int` type. For some reason, Go guys didn't support parsing non-numeric characters, resulting in a parse error when passing other kind of characters, like in this case with a dot. 

The invalid input param generates a default value = `0`, so there's no width / height value actually passed to `libvips`.

I [made](https://github.com/h2non/imaginary/commit/1acdf215640ad98b37aa5b287a462c990d392fbe) several minor refactors with tests to fix this, so now you can pass decimals and even negative numbers, the type parser will take care about them properly.

If you're using `imaginary` from Docker, let me know and I can push a new version to the registry.

**Comment by Dynom** [comment]
Sorry for the late reply, I decided to have a long "afk" weekend for a change (-; I am using the Docker image you provide, I'll be sure to roll out the new version and test the new features. Thanks again @h2non !

**Comment by h2non** [comment]
> Sorry for the late reply, I decided to have a long "afk" weekend for a change

No worries, that's totally fine! (btw I should follow you too :D)

I've just pushed a fresh `0.1.13` version to the Docker registry. Let me know if you need anything else. 

Enjoy. Cheers!
