### ISSUE TITLE
`/fit` an image incorrectly when upload with the JPEG image (converted from HEIC before uploading)

### ISSUE THREAD

**Issue by notsu** [h2non/imaginary#313]
# Tested on:

Imaginary Version: 1.2.1
# Here is the culprit image:
![image](https://user-images.githubusercontent.com/356022/84362710-dcecce00-abf7-11ea-9f27-8121c81eee53.jpg)

# Here is the result of resizing by using `/fit`:
<img width="1015" alt="Screen Shot 2563-06-11 at 15 28 13" src="https://user-images.githubusercontent.com/356022/84363150-7ddb8900-abf8-11ea-9d9c-95096cded124.png">

**Comment by h2non** [comment]
Since `v1.2.1` the default `extend` behavior is `copy` extended pixels. 

You can use one of the following options: black, copy, mirror, white, lastpixel and background.

Example (requires `imaginary` to run with `-enable-url-source` flag):

`http://localhost:9000/fit?width=300&height=300&type=jpeg&url=https://user-images.githubusercontent.com/356022/84362710-dcecce00-abf7-11ea-9f27-8121c81eee53.jpg&extend=mirror`

Would that work?

**Comment by notsu** [comment]
It works! Thanks 👍
