### ISSUE TITLE
Allow url image processing

### ISSUE THREAD

**Issue by gnewton** [h2non/imaginary#32]
Extend parameters to allow image to be a url that imaginary downloads, processes and returns to the API caller. 
 Should be off by default: use "-url" command line argument to turn on when starting imaginary

**Comment by h2non** [comment]
I've that feature in mind from the beginning, but I would prefer do not support it for three main reasons:

- Personally, I don't need it.
- I think the feature is outside of the core responsibility of `imaginary`, and that should be covered by high-level implementations that could use, after fetching images, process them via imaginary.
- I'd like to keep imaginary simple and focused in one thing: just process images. Fetching them is not its responsibility.

I totally agree that this feature is very useful in certain scenarios, and I don't totally reject it could be supported in a future, but for now I would prefer to keep it simple.

You can use a bunch of other solutions to fetch images, and then push them into a imaginary server for further processing, like you can do now with the [node.js client](https://github.com/h2non/node-imaginary).

BTW, I'm planning to build a more powerful service which will be responsible of fetching images (and persist, cache and so on), which will use `imaginary` behind the scenes for image processing. I'll let you know.

**Comment by gnewton** [comment]
My main reason for this request is for performance issues: if the image fetcher has to get the image and then has to submit the image to imaginary, there is an additional performance hit by sitting in-between.

Oh, BTW, this is really nice work! Thanks for creating this!  :-)

**Comment by h2non** [comment]
I agree, the performance constraint is the main goal to mitigate with this feature, however, as almost everything, it depends on each specific scenario. For instance, if your are running imaginary and the fetcher service in the same VPC, like in a specific region of AWS, you performance hit is almost insignificant since your I/O is so fast, even close to disk performance. In that scenario, your performance bottleneck is mostly probably in other place, not in the network.

As I said, I might support the feature in a future, but unfortunately at this time isn't my priority, however I'm very open to receive PRs. 
The unique requirements to accept a PR are:
- Don't create third-party dependencies (you can do everything using `net/http`)
- Be consistent and backwards compatible.
- Handles errors properly (network errors/timeouts, DNS errors, server errors)
- Properly tested, including some error/edge cases.

Thank you for the interest in the project!

**Comment by h2non** [comment]
This feature is now supported. You only have to pass the `-enable-url-source` to the binary.

Then you can simply perform a GET request passing the `url` query param, like in the following example:
```
curl http://localhost:8088/crop?width=600&height=400&url=https://github.com/h2non/imaginary/blob/master/fixtures/large.jpg -O image.jpg
```

See the [docs](https://github.com/h2non/imaginary#usage) for more details.
