### ISSUE TITLE
Cache of (some) processed images

### ISSUE THREAD

**Issue by gnewton** [h2non/imaginary#33]
Off by default, add a parameter that suggests the image be cached. For some use cases, like thumbnails, the produced image might be generated many times. Caching based on sha of image plus parameters applied might be useful for some.

**Comment by h2non** [comment]
Similar rationale like in #32. 

Caching strategies can be very sophisticated based on each particular scenario, and also rely on multiple storage layers. Implementing a caching layer in `imaginary` is outside of the scope the (micro)service, and adds an unnecessary complexibility and eventually could be error prone. 

IMHO, as engineer building some new system, I would prefer building a custom cache layer which fits better to my particular scenario and provides me more control, instead of rely on a generic implementation that probably can't fit all my needs.

You proposal is very reasonable, but as I wrote before, that feature should be supported in a high-level layer.

**Comment by gnewton** [comment]
I agree. Thanks.  :-)
