### ISSUE TITLE
Add support to specify caching headers

### ISSUE THREAD

**Issue by Dynom** [h2non/imaginary#37]
I would like to add caching headers to the responses from Imaginary. Caching-proxies often support these headers to determine the TTL in a certain edge.

Currently I work with immutable image resources (once generated, they never change, if they "change" they have a new unique identifier.). Because of that, a single set of caching-headers would suffice for me, but I can imagine other people would like to specify this dynamically.

I wouldn't mind contributing a PR with this feature, if that follows the design path you're on @h2non.

**Comment by h2non** [comment]
Please, see #33.

That being said, I don't have a clear idea about the scope of the feature you want to cover here.

**Comment by Dynom** [comment]
I don't propose a caching layer in Imaginary. Rather only HTTP caching headers.

So, whenever I do something like:
```
> GET /crop?width=290&height=218&file=c76/6ba/cf/6a0cb5df&type=jpeg&quality=85 HTTP/1.1
> Host: imaginary.example.org
> User-Agent: curl/7.43.0
> Accept: */*
>
```

The reply would read:
```
< HTTP/1.1 200 OK
< Content-Type: image/jpeg
< Date: Fri, 30 Oct 2015 08:56:17 GMT
< Server: imaginary 0.1.14 (bimg 0.1.19)
< transfer-encoding: chunked
< Connection: keep-alive
< Cache-Control: public, max-age=31536000
< Expires: Wed, 26 Oct 2016 22:00:23 GMT
< Last-Modified: Fri, 28 Aug 2015 21:45:00 GMT
< Vary: Origin
```

Where the last 4 headers would be the significant part.

Now that I think about it, just specifying a static list of arbitrary headers would be sufficient. But I'm now thinking if this is something Imaginary should support or not. I see some other use-cases (like origin identification), but I'm not sure if that justifies this feature.

**Comment by h2non** [comment]
I see now. In that case, this would be only valid when `imaginary` relies on the file system to read the images, so we can use [FileInfo](https://golang.org/pkg/os/#FileInfo) to retrieve the Last-Modified header, for instance.

Then, I believe we can simplify the other headers just adding an additional option with the cache TTL.
I believe that this should be only supported if `imaginary` is using the file system, otherwise is useless and incongruent.

I would not mind supporting this feature if it's clean and simple to use, so feel free to go ahead with a PR.

**Comment by Dynom** [comment]
Excellent. I'm fairly inexperienced with Go, but feel free to lay it on me in the PR (-:

Before I'll start I'll make s small specification to make sure it's heading the way you want.

**Comment by h2non** [comment]
Sounds great!
