### ISSUE TITLE
Unable to change port when running from docker

### ISSUE THREAD

**Issue by brunobasto** [h2non/imaginary#47]
When I run

sudo docker run -p 8080 -e "DEBUG=*" h2non/imaginary 

I get this log message

13:39:41.196 48us   47us   imaginary - imaginary server listening on port 9000

**Comment by sbani** [comment]
the port inside the docker container is 9000 (unless you change it with `-e "PORT=8080"`).
If you want to use the port 8080 you need to make sure docker is listening to port 8080 outside the container and forwards it to port 9000 inside the container.

```bash
sudo docker run -p 8080:9000 -e "DEBUG=*" h2non/imaginary
```

If you need to change the port inside the container sth like that should work:
```bash
sudo docker run -p 8080:9091 -e "PORT=9091" h2non/imaginary
```
But with this command you still use 8080 outside the container.

I made the container to run on "localhost" outside the container and therefore needed to changed the port because 9000 was blocked by another program.
```bash
sudo docker run --net="host" -e "PORT=8080" -p 127.0.0.1:8080:8080 h2non/imaginary
```
I also added that the container is listening on "127.0.0.1" only - just localhost.

Just to give you some examples. I'm totally new to dacker. There might be better solutions.

**Comment by brunobasto** [comment]
Thank you very much @sbani!

The first contact I had with docker was 10 minutes ago, so.. 

But thank you for the information.

**Comment by brunobasto** [comment]
@sbani 

Would you happen to know how can I pass the " -enable-url-source" to the instance running on docker

**Comment by sbani** [comment]
Just add it 

```bash
sudo docker run -p 8080:9091 -e "PORT=9091" h2non/imaginary -enable-url-source
```

Info from  [README](https://github.com/h2non/imaginary#docker)
